kFROM node:18-alpine

WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev --no-audit --no-fund || npm i --omit=dev
COPY . .

ENV NODE_ENV=production PORT=8080
EXPOSE 8080
CMD ["npm","start"]

