name: CI-CD (GCP Cloud Run)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  GAR_REPO: ${{ secrets.GAR_REPO }}
  REG_PATH: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPO }}
  BACKEND_IMAGE: ${{ env.REG_PATH }}/backend
  FRONTEND_IMAGE: ${{ env.REG_PATH }}/frontend
  BACKEND_SERVICE: backend
  FRONTEND_SERVICE: frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # Auth via OIDC
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Backend sanity
        working-directory: app/backend
        run: |
          npm ci
          node -e "console.log('backend ok')"

      - name: Frontend build sanity
        working-directory: app/frontend
        run: |
          npm ci
          npm run build

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./app/backend
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:latest
            ${{ env.BACKEND_IMAGE }}:${{ github.sha }}

      - name: Deploy backend
        run: |
          gcloud run deploy $BACKEND_SERVICE \
            --image="${BACKEND_IMAGE}:latest" \
            --region="$REGION" \
            --allow-unauthenticated \
            --set-env-vars=MONGO_URI="${{ secrets.MONGO_URI }}" \
            --quiet
          URL=$(gcloud run services describe $BACKEND_SERVICE --region "$REGION" --format='value(status.url)')
          echo "backend_url=$URL" >> $GITHUB_OUTPUT
        id: be

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./app/frontend
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:latest
            ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

      - name: Deploy frontend (inject BACKEND_URL)
        env:
          BACKEND_URL: ${{ steps.be.outputs.backend_url }}
        run: |
          gcloud run deploy $FRONTEND_SERVICE \
            --image="${FRONTEND_IMAGE}:latest" \
            --region="$REGION" \
            --allow-unauthenticated \
            --set-env-vars=BACKEND_URL="$BACKEND_URL" \
            --quiet

      # Optional: Trivy scans (soft-fail to start)
      - name: Trivy scan backend
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.BACKEND_IMAGE }}:latest
          format: 'table'
          exit-code: '0'
      - name: Trivy scan frontend
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.FRONTEND_IMAGE }}:latest
          format: 'table'
          exit-code: '0'
